### ISSUE TITLE
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False

### ISSUE THREAD

**Issue by aiqubo** [aakechin/NGS-PrimerPlex#1]
'''
 # Total number of constructed primers: 316890
 # Total number of different constructed primers: 24055
Analyzing primers for their specificity...
 Running BWA...
Traceback (most recent call last):
  File "NGS_primerplex.py", line 2947, in <module>
    specificPrimers,primersNonSpecRegionsByChrs=checkPrimersSpecificity(args.regionsFile[:-4],primersInfo,args.wholeGenomeRef,
  File "NGS_primerplex.py", line 1096, in checkPrimersSpecificity
    samFile=pysam.AlignmentFile(bwaResultFileName+'.sam')
  File "pysam/libcalignmentfile.pyx", line 736, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 985, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False
'''

Thank you for your great program, but it seems that there is an error,Is it something wrong?

**Comment by aakechin** [comment]
@aiqubo, could you please describe conditions of NGS-PrimerPlex use? Is it GUI, through docker or command-line? Which OS? Could you please try it with updated version?

P.S.: Sorry for the delayed answer.

**Comment by aiqubo** [comment]
> @aiqubo, could you please describe conditions of NGS-PrimerPlex use? Is it GUI, through docker or command-line? Which OS? Could you please try it with updated version?
> 
> P.S.: Sorry for the delayed answer.

Thank you for your kind feedback.
It isn't GUI，NGS-PrimerPlex use in centOS docker with Command-line version

**Comment by aakechin** [comment]
@aiqubo could you check if sam-file really does not include any reads in the output directory? If it is yes, please, check FASTQ-file, if there are any reads. If it includes reads, then you will have to try running BWA manually, maybe there is "Segmentation Fault" error.

**Comment by aiqubo** [comment]
@aakechin 
As follow,There is nothing in the sam-file,but the FASTQ-file has reads,So do I need to running BWA manually?
`-rw-rw-r-- 1 aiqubo aiqubo 6405891 Jan 11 18:03 he_NGS_primerplex_all_draft_primers.xls
-rw-rw-r-- 1 aiqubo aiqubo       0 Jan 11 18:03 he_NGS_primerplex_mutilplex_PCR_all_primers_sequences.bwa.sai
-rw-rw-r-- 1 aiqubo aiqubo       0 Jan 11 18:31 he_NGS_primerplex_mutilplex_PCR_all_primers_sequences.bwa.sam
-rw-rw-r-- 1 aiqubo aiqubo 2747472 Jan 11 18:03 he_NGS_primerplex_mutilplex_PCR_all_primers_sequences.fa
-rw-rw-r-- 1 aiqubo aiqubo   16727 Jan 11 18:03 he_NGS_primerplex_mutilplex_PCR.log`

**Comment by aakechin** [comment]
@aiqubo yes, if you can, run it please in a docker container. We need to catch an error that occurs during mapping primer sequences. Do you use the last version of NGS-PrimerPlex?

**Comment by hrstu** [comment]
Hi, I got the same error when running NGS_primerplex.py for the example gene list using the latest version of NGS-PrimerPlex through docker on my mac. Was there any resolution to this? 

Thanks!

`Reading input file...
 # Total number of input point regions: 45
 # Number of unique input point regions: 45
Creating input parameters for primer3...
Constructing primers...
100.0%
 # Total number of constructed primers: 59259
 # Total number of different constructed primers: 1417
Analyzing primers for their specificity...
 Running BWA...
Traceback (most recent call last):
  File "NGS_primerplex.py", line 3291, in <module>
    args.maxNonSpecLen,args.maxPrimerNonspec,False,'',args.blastNum)    
  File "NGS_primerplex.py", line 1297, in checkPrimersSpecificity
    samFile=pysam.AlignmentFile(bwaResultFileName+'.sam')
  File "pysam/libcalignmentfile.pyx", line 737, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 986, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False`

**Comment by hrstu** [comment]
Hi, I got the same exact error when running NGS_primerplex.py using the latest version of NGS-PrimerPlex through docker. I was running the command using the example_gene_list. The .fa file was successfully generated but the .bwa.sam and .bwa.sai files were present in the directory but empty. Was there ever a resolution to this? I am attaching my full error for reference. Thanks! 

Reading input file...
 # Total number of input point regions: 45
 # Number of unique input point regions: 45
Creating input parameters for primer3...
Constructing primers...
100.0%
 # Total number of constructed primers: 59259
 # Total number of different constructed primers: 1417
Analyzing primers for their specificity...
 Running BWA...
Traceback (most recent call last):
  File "NGS_primerplex.py", line 3291, in <module>
    args.maxNonSpecLen,args.maxPrimerNonspec,False,'',args.blastNum)    
  File "NGS_primerplex.py", line 1297, in checkPrimersSpecificity
    samFile=pysam.AlignmentFile(bwaResultFileName+'.sam')
  File "pysam/libcalignmentfile.pyx", line 737, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 986, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False

**Comment by aakechin** [comment]
Try the new version of the NGS-PrimerPlex: https://github.com/aakechin/NGS-PrimerPlex/releases/tag/v1.3.0
