### ISSUE TITLE
Designing external primers for embedded PCR

### ISSUE THREAD

**Issue by timoha15** [aakechin/NGS-PrimerPlex#13]
Hi!
I have a question about the embedded PCR primer design. I have a list of internal primers derived from NCBI Primer Blast (these were made well before NGS-PrimerPlex was published 😀). Now, I would like to design external primers for this list of primers. Is it possible at all, as my internal primer list is just a file with the primer sequences/gene names? Is there a way to construct a draft-file from this list of primers?

**Comment by aakechin** [comment]
@timoha15 Yes, you can write these primers into the XLS-file in the same format as NGS-Primerplex outputs them:
Amplicon_Number (1, 2, 3 etc.) | Left_Primer | Right_Primer | Amplicon_Name | Chromosome | Amplicon_Start | Amplicon_End | Amplicon_Length | Amplified_Block_Start | Amplified_Block_End | Left_Primer_Tm | Right_Primer_Tm | Left_Primer_Length | Right_Primer_Length | Left_Primer_GC | Right_Primer_GC | Desired_Multiplex
And then run the NGS-PrimerPlex with use of the file above as the -primers argument and with -embedded argument.
To get all these parameters, you can use our script checkPrimersForAllParameters (I added it to the repository).

**Comment by dominik-handler** [comment]
Hi, we tried to use the new script you added but we are running into problems with missing modules:
```
python3 /NGS-PrimerPlex/checkPrimersForAllParameters.py
Traceback (most recent call last):
  File "/NGS-PrimerPlex/checkPrimersForAllParameters.py", line 15, in <module>
    from primer_non_target_amplicons import getNonTargetAmplicons
ModuleNotFoundError: No module named 'primer_non_target_amplicons'
```

Thank you,
Dominik

**Comment by aakechin** [comment]
@dominik-handler Sorry, I forgot to add scripts that are imported in the checkPrimersForAllParameters.py script. I added them.

**Comment by timoha15** [comment]
Hi, 
I have a question about checkPrimersForAllParameters.py script: I am providing a list of primers for my genes of interest and it works for most of the genes. However, for a couple of genes I got the following error:
```{r}
ERROR: could not extract genome sequence!
b'/user/Genome/NGS_PrimerPlex/GRCm38.p6_genomic.fna'
NC_000079.6  80895801 80895923"
```

However, the primers are clearly in the sequence as you can see on the picture below:

<img width="1314" alt="Arrdc3" src="https://user-images.githubusercontent.com/80110653/112870945-10351680-90bf-11eb-9974-b8408fbb2b79.png">

Could you please advise what gets wrong here?
Thank you in advance!

P.S. That is the command I use:
```{r}
python3 /NGS-PrimerPlex/checkPrimersForAllParameters.py \
-in $list \
-wgref $genome 
```
$list is an xls.file that looks like this. Gene of interest was highlighted in bold for the screenshoot:
![List](https://user-images.githubusercontent.com/80110653/112871558-a8330000-90bf-11eb-90ce-6acb98a1f486.png)

**Comment by aakechin** [comment]
@timoha15 Maybe there is something wrong with the cell value with coordinate? Maybe it contains quotes?

**Comment by timoha15** [comment]
don't think so, as I this was stored in the txt file and then exported into excel to make an input file for the script. As the checkPrimersForAllParameters.py script does not recognise txt or tsv files as an input. Have really no idea why certain rows of the file are processed normally, and other rows give an error 😅

**Comment by aakechin** [comment]
@timoha15 the frequent problem :)

**Comment by aakechin** [comment]
@timoha15 the frequent problem :)
