### ISSUE TITLE
why so many output files?

### ISSUE THREAD

**Issue by robertwhbaldwin** [aakechin/NGS-PrimerPlex#14]
Hi,

I'm trying to understand why there's so many output files after running the NGS_primerplex.py script. 
My input regions had 10 rows/positions looking like this:

AWGY01000925.1	537	677	Af_SNP0003	1	B	NotW

And I ran the script like this:

python3 NGS_primerplex.py --threads 10 --regions-file ../AnoFim/10_SNP_positions --reference-genome ../AnoFim/Ano_assemb_filt.fna

What I got in the output were 42 files (one log file, one draft_primers.xls, and 10 sets of 4 files (two .xls and two .fa) named "combination_1" to "combination_10". Judging from the readme I was expecting one xls file. I have no idea what to do with all this output. Will someone please clarify what's going on? Thank You.

**Comment by aakechin** [comment]
@robertwhbaldwin if everything went right, you need only one of files ending with '_info.xls'. The program gives as many primer sets as it is defined in the -returnvariantsnum parameter. Sometimes the program cannot make primer sets that can be divided onto the number of multiplexes defined by user, so increasing -returnvariantsnum you can give it a chance to successfully make multiplexes. If you need only one primer set, you can set this parameter as 1.

**Comment by aakechin** [comment]
@robertwhbaldwin many of the output files can help to understand reasons why primers could not be designed or joined into primer pools. Below, I describe some output files:
_all_internal_primers_specificity.xls - this file contains the number of genome regions to which each primer can hybridize.
bwa.sam - this file can be viewed with less and genome coordinates to which some primer can hybridize can be extracted.
_primers_combination_1.fa - this file contains all primer sequences in FASTA-format. It may be useful for some additional primer analysis.
_amplicons_multiplex_incompatibility.xls - this file can be useful when some primer pairs cannot be sorted into any primer pools (multiplex reactions) and we want to see what problems prevent this. It can be primer-dimers, non-target amplicons, or amplicon overlapping. Sometimes, we can see that primer dimer is not critical and increasing -minmultdimerdg1 and/or -minmultdimerdg2 values we can skip weak primer dimers. In other cases, we can understand that we need to redesign only several primer pairs of our NGS-panel to overcome problems with sorting primers into pools.
info.xls - the main file with primers and primer parameters.
_internal_amplicons.fa - FASTA-file with sequences of internal amplicons +-100. It can be useful for the manual primer analysis.
