### ISSUE TITLE
How to add primers to previously desgined primer set?

### ISSUE THREAD

**Issue by robertwhbaldwin** [aakechin/NGS-PrimerPlex#15]
Thank You for the quick response in my first post. This is another question.

Suppose I designed a set of primers for some snps with NGS_primerplex and then order those primers. But now I'm given more snp positions that I also need primers for that will be multiplexed with the first set. How can you design primers for this second set that will be compatible with the first set? Is there a way to do this using the --draft option? Could you pass the first set in using the --draft option when you design primers for the second set? Or something like that? thanks - Robert

**Comment by aakechin** [comment]
@robertwhbaldwin Sorry for the such delay with answer... Yes, you can use the old primer set (*_info.xls file) in the -draft parameter.  Moreover, to save your time you can desing primers for new snps distinctly. Then manually join two *_info.xls files into one and two CSV-files with target regions into one CSV-file and run NGS-PrimerPlex for the joined set of SNPs using joined info.xls file as a draft-file.
In such variant, you will not have to check interactions between all primers (for old and new targets, and most of them will not be used in the final set) many times during primer design for new SNPs. And when you join two info.xls files into one, you will have to check them for interactions, but this will be done only for best primers selected previously which will take significantly less time.
