### ISSUE TITLE
NGS-Primerplex on Synology with Docker

### ISSUE THREAD

**Issue by JSeggewiss** [aakechin/NGS-PrimerPlex#17]
Hi!

Could anyboday let me know if it is possible to run NGS-PrimerPlex on a Synology with Docker installed?
Is there any manual and installation manual, respectively.

Best regards
Jo

**Comment by aakechin** [comment]
Hi @JSeggewiss! I think it should work although I haven't ever tried it. Maybe you could describe any issues that you think may prevent the NGS-PrimerPlex from running on the Synology?
