### ISSUE TITLE
[E::fai_retrieve] Failed to retrieve block: unexpected end of file

### ISSUE THREAD

**Issue by aiqubo** [aakechin/NGS-PrimerPlex#2]
'''--regions-file REGIONSFILE''' as follow:
'''
chr5    148206440       148206740       IHC     1,2
'''
Running BWA report an error
'''
Analyzing primers for their specificity...
 Running BWA...
 Processing SAM-file...
.........
56%^M46.65%^M46.74%[E::fai_retrieve] Failed to retrieve block: unexpected end of file
^M46.83%^M46.92%^M47.02%
'''
Could you tell me how to correct this error?

**Comment by aakechin** [comment]
@aiqubo, You can simply ignore this warning because when it occurs, NGS-PrimerPlex tries again, and if it success, process of checking primers continues. Unfortunately, I couldn't find how to turn off these warning messages.
