### ISSUE TITLE
Error message: not rechable from, when distributing the primers among multiplex reactions

### ISSUE THREAD

**Issue by avialee** [aakechin/NGS-PrimerPlex#20]
Hi, I am running NGS-PrimerPlex for snp sites with  enabling the amplicons splitted onto 2 multiplex reactions. But it failed for the region with dense snp sites, like this region:

![image](https://user-images.githubusercontent.com/35249396/124801573-92b85680-df89-11eb-883f-e6f0e1e81a62.png)

And here is the log file that gave the 'not reachable' error:

2021-07-07 08:42:56,073 - __main__ - INFO -  Searching for nonspecific amplicons that are formed by primers from different primer pairs...
2021-07-07 08:42:57,830 - __main__ - INFO - 20.0%
2021-07-07 08:42:58,673 - __main__ - INFO - 30.0%
2021-07-07 08:42:59,290 - __main__ - INFO - 50.0%
2021-07-07 08:42:59,878 - __main__ - INFO - 70.0%
2021-07-07 08:43:00,004 - __main__ - INFO - 80.0%
2021-07-07 08:43:00,066 - __main__ - INFO - 100.0%
2021-07-07 08:43:00,075 - __main__ - INFO -  # Number of primer pairs that form unspecific product: 92587
2021-07-07 08:43:00,076 - __main__ - INFO - Analyzing primers for covering high-frequent SNPs...
2021-07-07 08:43:12,346 - __main__ - INFO - 20.0%
2021-07-07 08:43:18,197 - __main__ - INFO - 30.0%
2021-07-07 08:43:30,018 - __main__ - INFO - 50.0%
2021-07-07 08:43:41,954 - __main__ - INFO - 70.0%
2021-07-07 08:43:47,854 - __main__ - INFO - 80.0%
2021-07-07 08:43:59,641 - __main__ - INFO - 100.0%
2021-07-07 08:43:59,668 - __main__ - INFO -
 Number of primers that do not overlap with high-frequent SNPs: 2531
2021-07-07 08:43:59,670 - __main__ - INFO -  Removing primer pairs covering high-frequent SNPs...
2021-07-07 08:44:00,257 - __main__ - INFO - Joining primer pairs to amplified blocks...
2021-07-07 08:44:00,304 - __main__ - INFO - Chromosome chr10 was splitted onto 8 distinct blocks
2021-07-07 08:44:10,413 - __main__ - ERROR -  Too low value of maximal overlap (-maxoverlap) or of initially designed primers (-primernum): 50 and 50. Try to increase one of them
2021-07-07 08:44:10,413 - __main__ - ERROR - 89693007 is not reachable from 89692793

I have no idea what is the best way to deal with this situation. Do you have any suggestions?

**Comment by aakechin** [comment]
@avialee Thank you for your question! There is no problems with SNPs in your case because the number of primer pairs that do not overlap with high-frequent SNPs 2531 and the primer design process continued. It means that all targets were covered after this step.

The error you received means that the program couldn't join primer pairs into one block. During this process it considers overlap between adjacent primer pairs (-maxoverlap). This parameter was initially introduced to control the number of primer pairs that we expect from the program. By decreasing it, you can force the program to design primer pairs as far apart from each other. But then this requires to design much more primers initially (-primernum parameter) and it takes much more time to analyze them at the next steps. However, now I suggest that this parameter may be excess and set it the same as the maximal amplicon length. You can try to set it as your maximal amplicon length too and see the result. If this error occurs again, do not hesitate to contact me again.

**Comment by avialee** [comment]
> @avialee Thank you for your question! There is no problems with SNPs in your case because the number of primer pairs that do not overlap with high-frequent SNPs 2531 and the primer design process continued. It means that all targets were covered after this step.
> 
> The error you received means that the program couldn't join primer pairs into one block. During this process it considers overlap between adjacent primer pairs (-maxoverlap). This parameter was initially introduced to control the number of primer pairs that we expect from the program. By decreasing it, you can force the program to design primer pairs as far apart from each other. But then this requires to design much more primers initially (-primernum parameter) and it takes much more time to analyze them at the next steps. However, now I suggest that this parameter may be excess and set it the same as the maximal amplicon length. You can try to set it as your maximal amplicon length too and see the result. If this error occurs again, do not hesitate to contact me again.

**Comment by avialee** [comment]
@aakechin  Thanks very much for your reply! I just realized that there were some warnings in the run:
WARNING! For input region PTEN_30 (chr10 89692910 89692911 PTEN_30) no primers left after filtering primers by specificity! Try to increase -primernum1 parameter. Or if you have already tried, use less stringent parameters.
WARNING! For input region PTEN_31 (chr10 89692913 89692918 PTEN_31) no primers left after filtering primers by specificity! Try to increase -primernum1 parameter. Or if you have already tried, use less stringent parameters.
WARNING! For input region PTEN_32 (chr10 89692923 89692924 PTEN_32) no primers left after filtering primers by specificity! Try to increase -primernum1 parameter. Or if you have already tried, use less stringent parameters.
WARNING! For input region PTEN_69 (chr10 89720708 89720709 PTEN_69) no primers left after filtering primers by specificity! Try to increase -primernum1 parameter. Or if you have already tried, use less stringent parameters.
WARNING! For input region PTEN_70 (chr10 89720732 89720734 PTEN_70) no primers left after filtering primers by specificity! Try to increase -primernum1 parameter. Or if you have already tried, use less stringent parameters.
WARNING! For input region PTEN_71 (chr10 89720740 89720741 PTEN_71) no primers left after filtering primers by specificity! Try to increase -primernum1 parameter. Or if you have already tried, use less stringent parameters.
Analyzing primers for covering high-frequent SNPs...

Is this the reason that result in the error of "89693007 is not reachable from 89692793"?  I tried another run with increased -maxoverlap as 180 which is the number I have set for the -maxampllen. But it still gave the same warning and error message.

**Comment by aakechin** [comment]
@avialee These warnings mean that for the listed positions, all primers designed are mapped  to at least one more region in the reference genome in addition to the target region. And yes, they can be the reason why "89693007 is not reachable from 89692793". Today, I'm going to upload the new version of the NGS-PrimerPlex. You can try it, maybe these warnings will disappear.

**Comment by aakechin** [comment]
Try the new version of the NGS-PrimerPlex: https://github.com/aakechin/NGS-PrimerPlex/releases/tag/v1.3.0
