### ISSUE TITLE
Primer design for long amplicon

### ISSUE THREAD

**Issue by Qianwangwoo** [aakechin/NGS-PrimerPlex#23]
Hi Team,

I'm very interested in your tool to design primer pairs for NGS data. I'm wondering that if I can use NGS-PrimerPlex to design primers for long amplicon, whose size is bigger than 15kb, and I'd like to target to whole region instead of one spot, such as SNP or short indels. I have tried to run it by the input below, but it failed to generate outcomes for me. any suggestion? I also attach the command line below, many thanks!

input.csv
chr1    155204239       155214653       target1     1,2     B       W
command line:
python3 NGS-PrimerPlex/NGS_primerplex.py --regions /data/input.csv -ref /database/ucsc_hg19/ucsc.hg19.fasta -blast -minampllen 10000 -maxampllen 15000 -run RUNNAME -th 5

**Comment by aakechin** [comment]
@Qianwangwoo Could you please send the command line output of the program?
