### ISSUE TITLE
Way to extract regions per position range or 5'UTR and 3'UTR only?

### ISSUE THREAD

**Issue by junwkim42** [aakechin/NGS-PrimerPlex#24]
Dear Dr. Kechin,

Thank you for building this great tool and sharing it with the public.
I was looking for a tool to build primers from a set of classical swine fever virus (CSFV) with set of complete genome sequences as a reference fasta and corresponding genebank(full) files from NCBI and came across your publication.

While following the tutorial, I noticed that my own set of Genbank(full) files for my CSFV reference are not as nicely labeled with genes as the ones in the fruit flies.

Two, for example are 
https://www.ncbi.nlm.nih.gov/nuccore/KP233071
https://www.ncbi.nlm.nih.gov/nuccore/KP233070

Where instead of specific genes, only 5'UTR CDS 3'UTR and their locations available. 

Are there anyways, to manually give location range to your software to extract regions or to have it reference the 5'UTR and 3'UTR in the features category instead of genes?
Or general recommendations for building primers with virus sequences using your software would be really appreciated.

Sincerely,

Scott Kim

Edit: removed draft

**Comment by aakechin** [comment]
@junwkim42 You can use directly the coordinates of regions that you are going to amplify in the next stage. I'm afraid that you will not be able to extract gene regions automatically with NGS-PrimerPlex. Unfortunately, it wasn't tailored for genomes with this level of annotation.
