### ISSUE TITLE
Gen Bank files for hg38, separated by Chromose

### ISSUE THREAD

**Issue by kiavash17** [aakechin/NGS-PrimerPlex#25]
Hi,

Thank you very much for sharing this great tool. I have used the linux version with hg19 and it works very well. 
For my application I need to use hg38.
I followed the instructions and have downloaded hg38.2bit, converted to FASTA, and indexed with BWA.
I would like to automatically extract genome regions and for this I need GenBank-files for each of chromosome. Can you please help me to find these files for hg38? I was only able to find: 
GCA_000001405.28_GRCh38.p13_genomic.gbff 
from: ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.28_GRCh38.p13/GCA_000001405.28_GRCh38.p13_genomic.gbff.gz

I'm wondering how I could divide this large file (for entire human reference genome) into individual chromosome files, or whether I can download files divided by chromosome from another source. 

Thank you.

**Comment by aakechin** [comment]
@kiavash17 Thank you for the question! Have you looked at Wiki pages? https://github.com/aakechin/NGS-PrimerPlex/wiki/NGS-PrimerPlex-installation-in-linux-as-a-standalone-tool. There is a detailed manual on how to prepare hg38 GenBank-files. Do not hesitate to contact me again, if some questions still remain.

**Comment by aakechin** [comment]
@kiavash17 Could you check your GenBank files e.g. with less command? The getGeneRegions.py script searches for 'gene' features. Do the files contain such GenBank features?
