### ISSUE TITLE
Intern Amplicons length does not overlap with amplicon length in info.xlsx

### ISSUE THREAD

**Issue by marcellosalvi** [aakechin/NGS-PrimerPlex#27]
Dear @aakechin I'm struggling in understanding what the programm mean for the internal amplicon file. I expected each sequence of 160 bp but I found more than 360 bp per amplicon. Could you explain me how is it possible?

**Comment by aakechin** [comment]
Dear @marcellosalvi Could you please write here the log file? There will be all the parameters that you used.

**Comment by marcellosalvi** [comment]
Thank you for your answer, I attached the log file. I set the optimal amplicon length at 160 bp, while the internal amplicon.fa has an average length of 330.

[list_cds.log](https://github.com/aakechin/NGS-PrimerPlex/files/7642105/list_cds.log)

**Comment by aakechin** [comment]
@marcellosalvi, I understood the problem. I remembered that the internal amplicon file contains internal amplicon sequences plus minus 100-150 bp to have an opportunity to move primer if it is necessary.

**Comment by marcellosalvi** [comment]
Thank you  @aakechin. So in order to allign them to check the coverage I have to remove the extra bp. Are they 100 or 150? On ehich depends?
ANd I would like to ask you also an other question: How do you choose the the primers? I see that the software produce ten different set of primer, which one I have to pick up?

**Comment by aakechin** [comment]
@marcellosalvi -100 and +100. Actually, many primers may be suitable, however, they are chosen based on the parameters that a user applies in the command and of course partially randomly among primers with equivalent parameters. So, you can choose any of the output primers.
