### ISSUE TITLE
path issue?

### ISSUE THREAD

**Issue by kday927** [aakechin/NGS-PrimerPlex#3]
I have repeatedly tried to run the test script.
It is trying to locate the hg19 directory containing the fasta.
Where should this directory be located?
within my hg19 directory:

ucsc.hg19.fasta      ucsc.hg19.fasta.ann  ucsc.hg19.fasta.pac
ucsc.hg19.fasta.amb  ucsc.hg19.fasta.bwt  ucsc.hg19.fasta.sa

# 1. Testing extraction of genome regions... #
ERROR! This test was finished with error!
ERROR (16)! Reference genome FASTA-file is absent:

/hg19/ucsc.hg19.fasta

[]

Downloaded chromosome fastas into hg19 folder. CHanged names to chr$.gb format.

WARNING! There was no table for converting gene name into chromosome.
ERROR (12)! Table for converting gene name into chromosome could not be created

**Comment by aakechin** [comment]
@kday927 Sorry for such a delay answer. Somehow I've not recevied any notifications about the issue by e-mail.
Could you please clarify, which version of the NGS-PrimerPlex do you use? Is it command-line or GUI? If command-line, is it the docker or the standalone version? Which OS?
Do you use arguments for the test.py script? There is one argument that is responsible for the path to the reference genome. Have you tried to use it?
