### ISSUE TITLE
Error (12) ! table for converting gene name into chromosome could not be created for bacterial genome

### ISSUE THREAD

**Issue by mhelbom14** [aakechin/NGS-PrimerPlex#30]
![2](https://user-images.githubusercontent.com/74139521/147875955-94f42cf1-eacf-420d-9814-e872710542df.PNG)
![1](https://user-images.githubusercontent.com/74139521/147875956-b07f02a5-19af-4887-80fb-2d6233e6dd27.PNG)
I am trying to develop an NGS panel for different bacteria for different genes.
I started with one bacteria and was trying to run 
[AB.zip](https://github.com/aakechin/NGS-PrimerPlex/files/7799064/AB.zip)
the tool using docker-desktop and wsl2. I ran the test script and it worked fine, as in the attached pictures.
but when I run the tool on my gene list and the bacterial ref sequence I keep getting the same error.
I modified the genebank file name to exactly match the chromosome name in the fasta file but the same error keep happening.

**Comment by aakechin** [comment]
Dear @mhelbom14. Thank you very much for your question and sorry for such a delay with an answer. The problem is in your GenBank-file. It should contain only one record. In your file, there is chromosome and plasmid sequences. You should separate them into two files.

**Comment by aakechin** [comment]
The first GB-file contains the plasmid, too, You only need to remove plasmid's sequence from it.
