### ISSUE TITLE
test.py on mac

### ISSUE THREAD

**Issue by sharmaee** [aakechin/NGS-PrimerPlex#31]
Received following error after download, install and running NGS-PrimerPlex/test.py:
### Global testing of almost all functions of NGS-PrimerPlex started (9 tests)! ###

# 1. Testing extraction of genome regions... #
Finished successfully but the output differs from the expected one!

Not clear why. 
ES

**Comment by aakechin** [comment]
@sharmaee Thank you for the question! It can be due to the previous issue. Did you use the last version? Also, could you show me  the content of the "test_gene.regions.csv" from the test directory?

**Comment by sharmaee** [comment]
the example scripts ran anway.
