### ISSUE TITLE
gene on chrx

### ISSUE THREAD

**Issue by sharmaee** [aakechin/NGS-PrimerPlex#32]
Hi, 
Encountered a bug while trying to find primers for a gene on the X chromosome. getGeneRegions.py works fine for other genes I've tried. 

While running getGeneRegions.py for a called ABCD1 I got the following errors: 
 GenBank file for chromosome chrX is absent in the reference directory hg19/!

hg19/chrX.gb hg19/chrX.gb.gz 24.gb or 24.gb.gz. 

This was strange because the file path was suddenly gone. 
So I changed the name of chr24.gb.gz to chrX.gb.gz and this resolved this bug but then the error changed to:

ERROR (8)! Gene with name "ABCD1" was not found in chromosome chrX

I redownloaded the genbank file for ChrX in case something was wrong with it and tried alternative names for ABCD1 but neither of those has changed the error message.

**Comment by sharmaee** [comment]
forgot to add: running using docker in command line and using reference genome hg19

**Comment by sharmaee** [comment]
tried a 3 other genes on the X chromosome with the same result.

**Comment by aakechin** [comment]
@sharmaee Thank you for the question! Could you write the command that you used? And is chrX.gb located in the directory specified with the -ref argument?
