### ISSUE TITLE
Unknown error with getting SNPs from the following file

### ISSUE THREAD

**Issue by FenrisdeAlioth** [aakechin/NGS-PrimerPlex#33]
Hello, 

I am having problems when checking the snps with the file downloaded from NCBI:

https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/

 I repeatedly get the following error:

```
ERROR (49)! Unknown error with getting SNPs from the following file. Possibly you haven't made tbi-file with tabix:
File: ../snp/common_all_20180418.vcf.gz
Chromosome: NC_000007.14
Start: 117587897
End: 117587926
```

I have the .tbi file also downloaded in the same location:

```
common_all_20180418.vcf.gz 
common_all_20180418.vcf.gz.tbi
```

What could be the problem?

Regards, and thank you very much!

**Comment by aakechin** [comment]
@FenrisdeAlioth Thank you for the question! Have you checked chromosome names in the reference file and the VCF-file with SNPs? Do they match? Maybe in the VCF-file chromosomes are chr1, chr2 etc. but in the reference file they are like NC_000007.14?

**Comment by FenrisdeAlioth** [comment]
Thank you very much for your quick response

I checked chromosome names as you suggest and i got the following results:

```
grep ">NC_000007.14" ../hg38/GRCh38_latest_genomic.fna
>NC_000007.14 Homo sapiens chromosome 7, GRCh38.p14 Primary Assembly
```
and at the VCF file:
```
7	193091	1245869	C	T	.	.	ALLELEID=1234538;CLNDISDB=MedGen:CN517202;CLNDN=not_provided;CLNHGVS=NC_000007.14:g.193091C>T;CLNREVSTAT=criteria_provided,_single_submitter;CLNSIG=Benign;CLNVC=single_nucleotide_variant;CLNVCSO=SO:0001483;GENEINFO=FAM20C:56975;MC=SO:0001623|5_prime_UTR_variant;ORIGIN=1
```
And as you say, the NCBI VCF file chromosome names are numbers, and at the fasta file from NCBI too has the accesion ID.

I changed the chromosome name on the reference genome from NC_000007.14 to 7 now it looks for the snps but them throws other error:

```
ERROR (60)! The following chromosome does not covered by any primer pair:
Chromosome as number: 7
Chromosome as string: NT_187366.1
```

This is the list of chromosomes on the reference genome:

```
1 NC_000001.11
2 NT_187361.1
3 NT_187362.1
4 NT_187363.1
5 NT_187364.1
6 NT_187365.1
7 NT_187366.1
8 NT_187367.1
9 NT_187368.1
10 NT_187369.1
11 NC_000002.12
12 NT_187370.1
13 NT_187371.1
14 NC_000003.12
15 NT_167215.1
16 NC_000004.12
17 NT_113793.3
18 NC_000005.10
19 NT_113948.1
20 NC_000006.12
21 7
22 NC_000008.11
...
...
```
Now it takes that my chromosome its the number 7 of the list instead the real chromosome 7 that its in the position 21, the one i have renamed from NC_000007.14 to 7.

Maybe it would be better make the changes on the VCF file, renaming the number of chromosomes for their NCBI accesion ID?

Any clue to solve it?

Thank you very much!

**Comment by aakechin** [comment]
@FenrisdeAlioth when you use only chromosome numbers (like "7" in your case), then the program takes the chromosome, which is the 7th in order in the file with reference sequences ("NT_187366.1" in your case). So, you can rename chromosome 7 from "7" to "chr7" in both reference genome file and VCF-file with SNPs. Or you can move this chromosome onto the 7th position in the reference file. Or, as you suggested correctly, you can rename all chromosomes in the VCF-file with their accession IDs.

**Comment by FenrisdeAlioth** [comment]
Finally I renamed the VCF chromosome names and works perfectly.

Thank you very much for your help!
