### ISSUE TITLE
¡Joining primer pairs to amplified blocks! problem

### ISSUE THREAD

**Issue by Setramis** [aakechin/NGS-PrimerPlex#34]
I'm stuck at the "Joining primer pairs to amplified blocks" phase. I am designing a multiplex of 29 pairs of primers (600 bp amplicon size), however, the Joining primer phase i) does not show the percentage of progress and ii) does not use the established nuclei (-th 6) iii) does not give me results for more than 24 hours. Is this normal?

What is the average time to obtain results? Since there is no information on the progress percentage, I don't know whether to turn off the computer or leave it longer.

Please I need your help.

Thank you
[gene_list_file.regions_v2.log](https://github.com/aakechin/NGS-PrimerPlex/files/8542043/gene_list_file.regions_v2.log)

**Comment by aakechin** [comment]
@Setramis Thank you for the question! The reason for such a long joining primer pairs to amplified blocks is the high number of primers that were designed before this stage (more than 70000!). Unfortunately, this stage could be divided into several threads only for targets located on several chromosomes that is not your case. However, to obtain relevant results you can change the "primernum1" parameter. It controls the number of primer pairs that are designed for one target (e.g. for one target position in your case). By default, it is 50 that is optimal for several dozen or hundreds of target positions. Try to set it as 3, 5, or 10.

**Comment by Setramis** [comment]
Thank you @aakechin, I will carry out the analyzes following your recommendations.
