### ISSUE TITLE
error ！ design embedded PCR primer

### ISSUE THREAD

**Issue by freshlearner** [aakechin/NGS-PrimerPlex#35]
Hi，
I get an error when i design an embedded PCR primer .
here are the error infos:

^M8.33%Traceback (most recent call last):
  File "/NGS-PrimerPlex/NGS_primerplex.py", line 3707, in <module>
    leftGC,rightGC,outputInternalPrimers[curRegionName][7]-(start+primersCoords[0][1])+1,
KeyError: 'GATA3_2_3'

and my input region file format is as follows:
chr10   8115672 8115873 GATA3_2         B       NW

Do you have any idea about the error ?
thank you for your help .

**Comment by aakechin** [comment]
@freshlearner, do you use the latest version? And do you have an empty column between "GATA3_2" and "B"? This empty column should mean that you don't need to sort your primers to multiplex sets.

**Comment by freshlearner** [comment]
Thanks for your reply.
I have an empty column between "GATA3_2" and "B" . and I use lastest docker images to run the program. 
here is my commands:
```
python3 /NGS-PrimerPlex/NGS_primerplex.py -regions targetRegion.v2.txt -ref /NGS-PrimerPlex/hg19/ucsc.hg19.fasta -blast --primers-number1 1000 --tries-to-get-best-combination 10000 --threads 20 --min-primer-melting-temp 57 --max-primer-melting-temp 63 --optimal-primer-melting-temp 60 --dntp-concentration 0.6 --divalent-concentration 1.5 --primer-concentration 50 --return-variants-number 1 --auto-adjust-parameters -skip --embedded-amplification
```

> @freshlearner, do you use the latest version? And do you have an empty column between "GATA3_2" and "B"? This empty column should mean that you don't need to sort your primers to multiplex sets.

**Comment by aakechin** [comment]
Try the new version of the NGS-PrimerPlex: https://github.com/aakechin/NGS-PrimerPlex/releases/tag/v1.3.0
