### ISSUE TITLE
error in test on a mac

### ISSUE THREAD

**Issue by luzhouyangge** [aakechin/NGS-PrimerPlex#37]
![Uploading 截屏2022-10-10 20.15.43.png…](error in test!)

**Comment by luzhouyangge** [comment]
<img width="582" alt="截屏2022-10-10 20 15 43" src="https://user-images.githubusercontent.com/115471575/194864873-cc4472a4-a1e6-43b5-b148-0c64ca4149a5.png">

**Comment by luzhouyangge** [comment]
<img width="793" alt="截屏2022-10-10 20 53 51" src="https://user-images.githubusercontent.com/115471575/194870873-ae44db39-2629-4c15-b73a-a2b97c6bf04d.png">

**Comment by luzhouyangge** [comment]
How to install on a MacOS ?

**Comment by aakechin** [comment]
@luzhouyangge Thank you for the question. Do use non-docker version? Then, you need to provide path to reference directory (with GenBank files) and to the whole genome reference with -ref and -wgref arguments. I will add this requirement to the test.py script. Thank you!

**Comment by luzhouyangge** [comment]
# 1. Testing extraction of genome regions... #
ERROR! This test was finished with error!
ERROR (16)! Reference genome FASTA-file is absent:

/NGS-PrimerPlex/hg19/ucsc.hg19.fasta

[]

Could you solve this problem on MacOS? Thank you

**Comment by aakechin** [comment]
@luzhouyangge try the latest version that I pushed 15 minutes ago

**Comment by aakechin** [comment]
Try the new version of the NGS-PrimerPlex: https://github.com/aakechin/NGS-PrimerPlex/releases/tag/v1.3.0
