### ISSUE TITLE
Definition of Primers_Score value

### ISSUE THREAD

**Issue by alicia-hg** [aakechin/NGS-PrimerPlex#38]
Hi! I would like to know the definition of the Primers_Score value that is calculated for each pair of primers in all the output drafts. With which values is calculated, and how? Lower value is better? Moreover, I would like to know if this value is used in posterior steps of the pipeline
Thank you so much!

**Comment by aakechin** [comment]
Hi @alicia-hg , the primers_score is a 'PRIMER_PAIR_PENALTY' that primer3 gives for each primer pair. Yes, lower is better. However, in posterior steps of the pipeline, it is not used. It was added in the NGS-PrimerPlex to use it later, however, this value turned out to be useless.
