### ISSUE TITLE
Joining steps running for ~90hrs on 80 cores

### ISSUE THREAD

**Issue by rolibudhwar** [aakechin/NGS-PrimerPlex#42]
@aakechin My program with the following parameters for longer amplicon is running for almost 90hrs and at 80 cores. Its stuck at Joining primer step. Could you pls help. Earlier the same program ran fine with smaller amplicon length(200bp) and the process was completed in 48hrs.

python3 NGS_primerplex.py -regions ./MTB/results.csv -ref ./MTB/MTB_genome.fna --min-amplicon-length 900 --max-amplicon-length 1100 --return-variants-number 1 --do-blast -th 80

Reading input file...
 # Total number of input point regions: 23644
 # Number of unique input point regions: 23644
Creating input parameters for primer3...
Constructing primers...
100.0%
 # Total number of constructed primers: 24075642
 # Total number of different constructed primers: 236226
Analyzing primers for their specificity...
 Running BWA...
 Processing SAM-file...
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file[E::fai_retrieve] Failed to retrieve block: unexpected end of file

[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
12.8%[E::fai_retrieve] Failed to retrieve block: unexpected end of file
100.0%
 # Total number of nonspecific regions: 257711
 Searching for nonspecific amplicons that are formed by designed primer pairs...
 # Number of specific primer pairs: 235962
 Removing unspecific primer pairs...
 Searching for nonspecific amplicons that are formed by primers from different primer pairs...
100.0%
 # Number of primer pairs that form unspecific product: 848617
Joining primer pairs to amplified blocks...
0.0%

**Comment by aakechin** [comment]
@rolibudhwar Try to decrease -primernum1 parameter. It defines the number of primer pairs that are designed for each target. You have many targets, so the number of primers that it designed is also too large. Decrease it to 2-3, make primers. And if there are some targets without primers, use primers designed previously as -draft and run it again with 5-10 -primernum1 argument.
