### ISSUE TITLE
primers_combination_1_info.xls chromosome coordinate inconformity

### ISSUE THREAD

**Issue by kr1stoff** [aakechin/NGS-PrimerPlex#50]
Hi,
@aakechin First of all, thank you for the tools!

I had a Problem when designing the primers, one row(name Exophiala dermatitidis-3-31 in region bed) of primers_combination_1_info.xls Amplicon_Start and Amplicon_End coordinate system is different from the other rows. Other rows like 1-based coordinate system, i use `samtools faidx`  Chrom:Amplicon_Start-Amplicon_End query region, the sequence is consistent with Left_Primer_Seq and Right_Primer_Seq. but "Exophiala dermatitidis-3-31" not. the primers_combination_1_info.xls  Chrom,Amplicon_Start,Amplicon_End is "NW_008751655.1,113,312". in practice, real coordinate is  "NW_008751655.1,114,313" by `samtools faidx` manual check. WHY?? 

Command line
```
python3.8 NGS-PrimerPlex-1.3.3/NGS_primerplex.py -ref Exophiala-dermatitidis-5970/5970/ref.fna -region design/2tNGS.bed -th 100 -primernum1 10 -blast -minampllen 175 -maxampllen 250 -optampllen 200 -minprimerlen 18 -maxprimerlen 28 -optprimerlen 23 -minprimermelt 63 -maxprimermelt 67 -optprimermelt 64 -minprimergc 30 -maxprimergc 70 -optprimergc 50 -minprimerendgc 0 -maxprimerendgc 5 -maxprimerpolyn 5  -maxoverlap 300 -returnvariantsnum 5 -skip
```
REF is Exophiala dermatitidis reference genome sequence, BED as follow
```
...
NW_008751655.1  212     286     Exophiala dermatitidis-3-1      1       B       W
NW_008751655.1  212     287     Exophiala dermatitidis-3-11     1       B       W
NW_008751655.1  212     289     Exophiala dermatitidis-3-21     1       B       W
NW_008751655.1  201     286     Exophiala dermatitidis-3-31     1       B       W
...
```
primers_combination_1_info.xls
```
#	Left_Primer_Seq	Right_Primer_Seq	Amplicon_Name	Chrom	Amplicon_Start	Amplicon_End
...
61	GTTCTGTGCATTACCAACGTGAC	CTGTCGACCTGGGATTTGAGAAT	Exophiala dermatitidis-3-31	NW_008751655.1	113	312
62	GCATTGCAGCCATGAACGGA	CACTCAGACCCACCAGCAAG	Exophiala dermatitidis-2-46	NW_008751655.1	269	468
63	GAGATGTCGTTGTCTGGATTATGTTG	GCCAGCCAACCCTGAACT	Exophiala dermatitidis-2-10	NW_008751655.1	346	546
64	TTCTTCCTCCAGCAGTTGTTTCA	ACAATGCCCCGTTTGCTGT	Exophiala dermatitidis-8-45	NW_008751655.1	2658	2857
...
```

Looking forward to your reply!

**Comment by aakechin** [comment]
@kr1stoff Thank you very much for your issue report. There was really a mistake for primers that start near the start of the reference sequence. Increase by one was absent there. The updated version is available now. Thank you!

**Comment by kr1stoff** [comment]
Well, i ran the script again and it looks fixed. thanks!

**Comment by kr1stoff** [comment]
resolved
