### ISSUE TITLE
amplicon length assignment

### ISSUE THREAD

**Issue by gooodle** [aakechin/NGS-PrimerPlex#7]
I like to try the script to design primers for amplicon sequencing. Just wondering if it is possible to define different lengths for different amplicons. The description implies that the length defined by- maxampllen shoulkd be applied to all amplicons. Thanks.

**Comment by aakechin** [comment]
@gooodle, you can split your target regions onto several TSV-files with regions and run them separately. When all primers are finished, you can merge the XLS-file with primers obtained into one file and use it as draft primers to combine them into several primer pools.

**Comment by gooodle** [comment]
Good idea, thanks.
