### ISSUE TITLE
typos in manual?

### ISSUE THREAD

**Issue by wenzhan510** [aakechin/NGS-PrimerPlex#9]
I believe there are two typos in your `read.me` file:

single and double quote?
`docker run -it --entrypoint 'bash' --name ngs_primerplex_ref -v '<directory where you are going to design new primers>:<name of this directory in the container>" aakechin/ngs-primerplex:latest`

`unzip` VS `gunzip`?
`unzip NGS-PrimerPlex/hg19/ucsc.hg19.fasta*.gz`

**Comment by aakechin** [comment]
@wenzhan510 Thank you! I fixed this mistake. You need to use namely gunzip because the archives were created with gzip instead of zip
